name: petty_app
description: A new Flutter application.
publish_to: "none"
version: 1.0.2+3
environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  rxdart: ^0.27.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_swipable: 
  cloud_firestore: ^4.3.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.0
  libphonenumber: ^2.0.2
  flutter_datetime_picker: ^1.4.0
  flutter_spinkit: ^5.1.0
  flutter_multi_formatter: ^2.5.7
  outline_gradient_button: ^2.0.0+1
  file: ^6.1.4

  connectivity_plus: ^2.3.0
  #remove one date time picker
  date_time_picker: ^2.1.0
  table_calendar: ^3.0.3
  flutter_neumorphic: ^3.2.0

  fluttertoast: ^8.0.8

  #can be deleted
  #  video_player: ^2.3.0

  flutter_swiper: ^1.1.6
  get:
  uuid: ^3.0.5
  flutter_range_slider: ^1.4.0
  font_awesome_flutter: ^10.0.0
  flutter_tindercard: ^0.2.0
  cached_network_image: ^3.2.0
  scrolling_page_indicator: ^0.1.2
  syncfusion_flutter_datepicker: ^19.3.59
  syncfusion_flutter_sliders: ^19.3.59
  flutter_xlider:
  flutter_html:

  filter_list: ^1.0.0
  carousel_pro: ^1.0.0
  flutter_svg: ^1.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.13
  flutter_stripe: ^2.5.0

  shimmer: ^2.0.0
  dotted_border: ^2.0.0+2
  form_validator: ^1.0.2
  firebase_auth: ^4.2.6
  #  place_picker: ^0.9.18 add ios part
  provider: ^6.0.2
  image_picker: ^0.8.4+11
  #  add ios part
  file_picker: 
  story_view: ^0.13.2
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^9.4.0
  audioplayers: ^0.20.1
  flutter_facebook_auth: ^4.3.0
  emoji_picker_flutter: ^1.1.2
  characters:
  auto_size_text: ^3.0.0

  # google_maps_flutter:
  # geolocator:
  # google_maps_webservice:
  # tuple:
  # flutter_styled_toast: ^1.2.1
  #    firebase_storage: ^3.1.6
  #google_maps_flutter: ^0.5.30
  #google_map_location_picker: ^3.3.4
  #location: ^1.4.1
  # cloud_firestore:
  #cloud_firestore:
  #firebase_auth: ^0.14.0+5
  # cloud_firestore: ^0.12.9+4
  #firebase_storage:
  #firebase_dynamic_links:
  # firebase_dynamic_links: ^0.5.1
  #firebase_database:
  #firebase_core:
  #flutter_localizations:
  #  sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pett_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/categories_icons/
    - assets/userimages/
    - assets/avatars/
    - assets/flags/
  fonts:
    - family: SF-UI-Display-Regular
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.otf
    - family: myfonts
      fonts:
        - asset: assets/fonts/sf-ui-display-light-58646b33e0551.otf
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/sf-ui-display-medium-58646be638f96.otf